### ISSUE TITLE
`paint.html` demo throws an error

### ISSUE THREAD

**Issue by therealjtgill** [cedric-h/linear-webgl#1]
Tried loading the `paint.html` demo and got this error in the console:

```
Uncaught Error: Types of varying 'v_uv' differ between VERTEX and FRAGMENT shaders.
error: vertex shader output `_uv_uv' declared as type `vec2', but fragment shader input declared as type `vec3'


    at createProgram (paint.html:115:19)
    at paint.html:137:17
```

Not sure if this helps, but I'm running Chrome Version 124.0.6367.118 (Official Build) (64-bit)

**Comment by aolo2** [comment]
+1 on this one for Chromium 124 and Firefox 125 on Linux

**Comment by cedric-h** [comment]
Damn, this works fine on Windows and MacOS, but not on iOS 🤔 

Interestingly, that varying isn't even used!

I fixed it with this commit, checking to see if it works on iOS now ...

https://github.com/cedric-h/linear-webgl/commit/fb1acb68435bb5b8e6a519f9f8e55ccfa1e5233a

**Comment by cedric-h** [comment]
It still doesn't work on my phone, I'm going to try to get an error message off of it in a couple hours.

Thanks so much for the error report, folks! <3
